package com.jTranProc.Common.Enums;

public enum ServiceType {

    SVC_TCP_SERVER,
    SVC_TRAN_HANDLER,
    SVC_DELIMITED_PARSER,
    SVC_JSON_PARSER,
    SVC_REST_CLIENT,
    SVC_TCP_SERVER_RESPONSE,
    SVC_TRAN_HANDLER_RESPONSE,
    SVC_DELIMITED_PARSER_RESPONSE,
    SVC_JSON_PARSER_RESPONSE;
}
